name: GitHub Actions Demo
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: condaforge/mambaforge:latest
    steps:
      - run: apt-get update && apt-get install git
      - run: git clone git@github.com:pydata/xarray.git
      - run: cd xarray
      - run: mamba env create -f ci/requirements/doc.yml
      - run: cd doc
      - run: conda activate xarray-docs && make html
